### ISSUE TITLE
Update Goreleaser CI workflow and config

### ISSUE THREAD

**Issue by Spill-Tea** [google/addlicense#190]
Since this project has been revived, the API and config yaml need to be updated to correctly build the project using Goreleaser.

1. `--rm-dist` arg has been deprecated and replaced with `--clean`
```yaml 
# release.yaml
  - name: Run GoReleaser
     uses: goreleaser/goreleaser-action@5a54d7e660bda43b405e8463261b3d25631ffe86 #v2.7.0
     with:
       distribution: goreleaser
       version: '~> v1'
       args: release --clean
     env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

2. The config file needs to be updated. The `replacements` key within the `archives` section has been [deprecated](https://goreleaser.com/deprecations/#archivesreplacements), in favor of `name_template`. I think it might look something like this:

```yaml
# .goreleaser.yaml
archives:
  name_template: >-
      {{- .ProjectName }}_
      {{- .Tag }}_
      {{- if eq .Os "darwin" }}macOS_
      {{- else if eq .Os "windows" }}Windows_
      {{- else if eq .Os "linux" }}Linux_
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
```
